###############################################################################
#
# command_line_test.py
#
# Tests to verify that the command line handles various flags and/or problems
# correctly.
#
# (c) 2024 Zachary Kurmas
#
###############################################################################

import system_test_base

class TestCommandLine(system_test_base.SystemTestBase):

    def test_no_parameters(self):
        result = self.run_plnq([], expect_empty_stderr=False)

        expected_stderr = 'usage: plnq [-h] [-v] [--destroy] [--uuid UUID] [--show-notebook-output] [--task-indexes] filename [dir_name]\nplnq: error: the following arguments are required: filename'
     
        # The return value and message are determined/generated by the argparse library
        self.assertEqual(2, result.returncode)
        self.assertEqualIgnoreWhitespace(expected_stderr, result.stderr)
        self.assertEqual([], result.stdout_lst)

    def test_no_such_file(self):
        result = self.run_plnq(['no_such_file.ipynb'])
        self.assertEqual(1, result.returncode)
        self.assertEqual(f"Input 'no_such_file.ipynb' doesn't exist.", result.stdout_lst[0])

#
# How to test where output goes?
#


if __name__ == '__main__':
    import unittest
    unittest.main()